### PR TITLE
Created Landing Page

### PR DESCRIPTION
**Pull request by HimanshuTembhe**
#8

### CODE REVIEW

**Comment by deepak-2605** [comment]
@HimanshuTembhe UI is not responsive . You can make changes in Figma design to make it responsive for small and medium screen devices.

**Comment by deepak-2605** [comment]
@HimanshuTembhe  UI is not responsive for small and medium screen devices. Make it responsive.

**Comment by HimanshuTembhe** [comment]
Working on it

**Comment by deepak-2605** [comment]
In a mobile view, the four images can be positioned beneath the login button section. Additionally, there is non-uniform spacing between the images on small and medium-sized screens.

**Pull request merged**
