### PR TITLE
Fix. Phone number validation and minor-bugs-2

### PR DESCRIPTION
**Pull request by DebidYadav**

### CODE REVIEW

**Comment by AnkitGurwan** [comment]
Okay. We can't go on merging small commits each time.
Can you remove some minor-bugs written in issue-minor-bugs2, that will hardly take 30 minutes. Will assign you that if you want?

**Comment by DebidYadav** [comment]
> We can't go on merging small commits each time. Can you remove some minor-bugs written in issue-minor-bugs2, that will hardly take 30 minutes. Will assign you that if you want?

Ok

**Comment by AnkitGurwan** [comment]
Kindly add these changes in that issue/PR. 
Will merge that PR.

**Comment by AnkitGurwan** [comment]
Mention yourself in that issue, will assign you after.
Make the PR by today EOD as it's a beginner issue. We will assign to else otherwise.

**Comment by AnkitGurwan** [comment]
Login button is even bad than earlier.
Project section styling is unchanged which was supposed to be done as per issue.

**Comment by DebidYadav** [comment]
Add specific instructions to how the button should be or attach any
screenshots.

**Pull request merged**
