### PR TITLE
Add navbars design 2

### PR DESCRIPTION
**Pull request by Dhruv127**

### CODE REVIEW

**Comment by deepak-2605** [comment]
Designs of navbar are good. But, there are some issues with UI which were not there earlier. "Portfolio Generator" was at centre. There are some issues with scrollbar also. In dark mode, due to same color of text and input ,text is illegible at some places.

**Comment by Dhruv127** [comment]
I have corrected it , please check now.

**Comment by AnkitGurwan** [comment]
@dhruv 
Design is looking good but kindly read the issue again. We want different designs of the navbar. Placing the text left, center or right do make it look different but these silly things are not expected by us from the assignee. 
Don't go for many, create one more different design of navbar i.e. given in description-toggled navbar (current one's are fixed) or any other design which is different from designs we are already having. 
Do let us know if you have any confusion.

**Comment by Dhruv127** [comment]
Yes , in the issue , it's written to make different designs like horizontal navbar,  toggle navbar at left (which is current one ig) . I can't think of many designs so try giving different styles to horizontal navabr design only . Also the link shared by deepak , contains mostly horizontal navbars design if we look wrt to project where there are no dropdown and all . Can you please explain a little what you are looking for ?

**Comment by AnkitGurwan** [comment]
We don't want completely new design but atleast these should not be similar.
 
1.You can create a toggled navbar which get toggled from left in large screen and from top in small, medium screens.
2. You can create a fixed navbar at top which is fixed in all screens i.e. small, medium, large screens (each current design is having toggle in small, medium screen).

**Comment by Dhruv127** [comment]
Please check:
Design1: toggled from left in small, medium screens.
Design 2: orignial one
Design 3: a fixed navbar at top which is fixed in all screens i.e. small, medium, large screens.
Design 4: for small screen it has toggle and for medium and large horizontal navbar.

**Comment by Dhruv127** [comment]
I didn't understand what you wanted to convey with the toggle from the left on a large screen. Please check if this design works.

**Comment by AnkitGurwan** [comment]
By toogle from left, i didn't mean to have toggle button on left, but to toggle the content horizontally i.e. left to right.

Still, designs are okay. It would be great if you can also show on which navbar is selected. Currently, it's not possible to find out which navbar is selected without looking in preview or downloading file.

**Comment by Dhruv127** [comment]
yr , sorry I still really don't understand this. Toggle left to right ?.. instead of opening the toggle window vertically from top to down, u mean to open it from left to right. I have not seen like this so .. like this what you want?

**Comment by Dhruv127** [comment]
However, i have done the navbar selection part, if you can see it And merge the PR.

**Pull request merged**
