### PR TITLE
Change section Name functionality

### LINKED ISSUE #11: Change the name of sections
Give an option to user to rename sections i.e. Experience, Education, Skills to whatever he wants. For example : User can rename **Experience** section to **My Work**.

**NOTE: Do write comments in your code and write the code in separate files and import those files in the main page. Give meaningful names to files and variables .
Kindly avoid the authentication for now. Directly go to http://localhost:3000/portfolio**

### PR DESCRIPTION
**Pull request by Tushar98644**
fixes #11

### CODE REVIEW

**Comment by AnkitGurwan** [comment]
@Tushar98644 Also reflect the live changes in the code and preview part of portfolio too.

**Comment by Tushar98644** [comment]
> @Tushar98644 Also reflect the live changes in the code and preview part of portfolio too.

Done, i presumed earlier that the form was already mapped to the preview file . Anyways ,updated the preview with redux

**Comment by AnkitGurwan** [comment]
You are almost there. Lastly update the **live code** as well as you did for preview.

**Comment by Tushar98644** [comment]
> You are almost there. Lastly update the **live code** as well as you did for preview.

oh sorry about that , updated

**Comment by AnkitGurwan** [comment]
@Tushar98644 it would be amazing if you can change the navbar name too in code and preview.
They also need to be changed as well.

**Comment by Tushar98644** [comment]
> @Tushar98644 it would be amazing if you can change the navbar name too in code and preview. They also need to be changed as well.

updated , sorry too careless of me to not notice . I would suggest expanding the code and preview window for a better view,  there is white space left in that area and  decrease the font size a bit

**Comment by Tushar98644** [comment]
@deepak-2605 @AnkitGurwan kindly add the hactoberfest-accepted labels to all the merged prs

**Pull request merged**
