### PR TITLE
Fix 33 : add-projects-design

### PR DESCRIPTION
**Pull request by Dhruv127**

### CODE REVIEW

**Comment by Dhruv127** [comment]
For large screen
Screenshot (212)
for medium screen
Screenshot (213)
can you please tell specifically what should i change?

**Comment by Dhruv127** [comment]
Although, I added the theme color effect.

**Comment by deepak-2605** [comment]
@Dhruv 127 This looks good . But , if description of one of the project is long , then try to  keep other project at centre. Right now, they are aligned at top.

**Comment by Dhruv127** [comment]
do check if this what you are looking for.

**Comment by deepak-2605** [comment]
UI is not similar to what it was earlier. Please look into that.

**Comment by Dhruv127** [comment]
Can you please tell specifically what UI is changed, i am not able to find out . 
Screenshot (214)
Screenshot (216)

**Comment by Dhruv127** [comment]
?

**Pull request merged**
