### PR TITLE
hacktoberfest : Design

### PR DESCRIPTION
**Pull request by Anureng**
I completed all the changes , but for this "Make the design of project section similar to others in home page" problem i didn't get properly .

### CODE REVIEW

**Comment by AnkitGurwan** [comment]
Actually the project section doesn't have similar input boundaries. Also, text color is not perfect in dark mode.

**Comment by Anureng** [comment]
Done with project section UI ,  you can check 
8b1778c34bd0554472a5c9b0fca39975156160c7

**Comment by AnkitGurwan** [comment]
@Anureng 
1. Scroll is still there on login page.
2. Microsoft logo on login button still not good
3. In project section, few inputs still requires a gap.
4. Style not changed for add and remove section buttons on the home page
5.  Successful entry of skills, put "cross" inside box in which skill is written.

**Comment by AnkitGurwan** [comment]
Kindly do it by today EOD as these are very basic issues and they don't requires much time.

**Comment by AnkitGurwan** [comment]
Reply to this message, if you are having any confusion or you are working on it. 
We don't want to de-assign you considering your contribution and efforts but we can't wait for too long for a beginner issue.

**Comment by Anureng** [comment]
I am working on it by EOD i will give you . For this one "Scroll is still there on login page." can you give me the image , i am not getting this properly .

**Pull request closed without merging**
