### PR TITLE
added dark theme for portfolio page

### PR DESCRIPTION
**Pull request by Shifat-Ali**
Hey @deepak-2605 ,
I have added dark theme of portfolio page and it stores theme state on refresh as well.
Here is screenshot of portfolio page in dark theme
localhost_3000_portfolio

### CODE REVIEW

**Comment by deepak-2605** [comment]
In dark mode, There is some issue when we are changing name of section . Please look into that.

**Comment by Shifat-Ali** [comment]
Hey @deepak-2605 ,
Can you explain a bit that what's the issue.

**Comment by deepak-2605** [comment]
In dark mode, try to change the name of a section by clicking on that section. For example, click on "Education" to modify its name in the portfolio. You will notice that the color of the input field and text is the same, making the text illegible. This is the issue.

**Comment by Shifat-Ali** [comment]
Hey @deepak-2605 ,
I have fixed it, please look into it once and let me know if there any other issue as well

**Pull request merged**
